name: Reusable - Test

on:
  workflow_call:
    inputs:
      os:
        description: 'The operating system to test on'
        required: true
        type: string
      python-version:
        description: 'The Python version to use'
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ inputs.os }}

    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies on MacOS
        if: inputs.os == 'macos-latest'
        shell: bash
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install numpy scipy
          python -m pip install --upgrade pip wheel setuptools
          pip install pytest pytest-timeout

      - name: Install dependencies
        if: inputs.os != 'macos-latest'
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel
          pip install pytest pytest-timeout

      - name: Download wheels artifact
        uses: actions/download-artifact@v4
        with:
          name: fluctuation-analysis-tools-${{ inputs.os }}-${{ inputs.python-version }}
          path: wheelhouse

      - name: Install FluctuationAnalysisTools from wheel
        shell: bash
        run: |
          pip install wheelhouse/*.whl

      - name: Run tests
        run: |
          mkdir -p test-results
          pytest tests/ --junitxml=test-results/${{ runner.os }}.xml -v

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ runner.os }}
          path: test-results/
