name: Reusable - Build Wheels

on:
  workflow_call:
    inputs:
      os:
        description: 'The operating system to build on'
        required: true
        type: string
      python-version:
        description: 'The Python version to use'
        required: true
        type: string
    outputs:
      artifact-name:
        description: 'The name of the uploaded artifact'
        value: ${{ jobs.build-wheels.outputs.artifact-name }}

permissions:
  contents: read

jobs:
  build-wheels:
    runs-on: ${{ inputs.os }}

    outputs:
      artifact-name:
        value: fluctuation-analysis-tools-${{ inputs.os }}-${{ inputs.python-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build wheels
        if: inputs.os != 'ubuntu-latest'
        run: |
          python -m build --wheel --outdir wheelhouse

      - name: Repair Linux wheels
        if: inputs.os == 'ubuntu-latest'
        run: |
          python -m build --sdist --outdir sdisthouse

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fluctuation-analysis-tools-${{ inputs.os }}-${{ inputs.python-version }}
          path: ./wheelhouse/*.whl

      - name: Upload sdist as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fluctuation-analysis-tools-${{ inputs.os }}-${{ inputs.python-version }}
          path: ./sdisthouse/*.tar.gz
