name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit-validation:
    uses: ./.github/workflows/reusable/pre-commit-validation.yml

  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
      fail-fast: false

    uses: ./.github/workflows/reusable/build-wheels.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    needs: pre-commit-validation

  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.11"
            artifact-name: fluctuation-analysis-tools-ubuntu-latest-3.11
          - os: windows-latest
            python-version: "3.11"
            artifact-name: fluctuation-analysis-tools-windows-latest-3.11
          - os: macos-latest
            python-version: "3.11"
            artifact-name: fluctuation-analysis-tools-macos-latest-3.11
      fail-fast: false

    uses: ./.github/workflows/reusable/test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    needs: build-wheels
