name: Test and Release

on:
  push:
    tags:
      - 'release/[0-9]+.[0-9]+.[0-9]+*'
permissions:
  contents: read
jobs:
  pre-commit-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-precommit-${{ hashFiles('**/pyproject.toml', '**/.pre-commit-config.yaml') }}
          restore-keys: |
            pip-precommit-

      - name: Install pre-commit
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit validation
        shell: bash
        run: |
          pre-commit run --all-files

  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    needs: pre-commit-validation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build wheels
        if: matrix.os != 'ubuntu-latest'
        run: |
          python -m build --wheel --outdir wheelhouse

      - name: Repair Linux wheels
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m build --sdist --outdir sdisthouse

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fluctuation-analysis-tools-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl

      - name: Upload sdist as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fluctuation-analysis-tools-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./sdisthouse/*.tar.gz


  test:
    needs: build-wheels
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on MacOS
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install numpy scipy
          python -m pip install --upgrade pip wheel setuptools
          pip install pytest pytest-timeout

      - name: Install dependencies
        if: matrix.os != 'macos-latest'
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel
          pip install pytest pytest-timeout

      - name: Download wheels artifact
        uses: actions/download-artifact@v4
        with:
          name: fluctuation-analysis-tools-${{ matrix.os }}-${{ matrix.python-version }}
          path: wheelhouse

      - name: Install FluctuationAnalysisTools from wheel
        shell: bash
        run: |
          pip install wheelhouse/*.whl

      - name: Run tests
        run: |
          mkdir -p test-results
          pytest tests/ --junitxml=test-results/${{ runner.os }}.xml -v

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ runner.os }}
          path: test-results/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get release name
        id: get-release
        run: |
          TAG=$(git describe --tags --abbrev=0)
          RELEASE_NAME=$(echo "$TAG" | sed 's|^release/||')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Download sdist artifact
        uses: actions/download-artifact@v4
        with:
          pattern: fluctuation-analysis-tools-*.tar.gz
          path: ./artifacts

      - name: Download wheels artifact
        uses: actions/download-artifact@v4
        with:
          pattern: fluctuation-analysis-tools-*
          path: ./artifacts

      - name: Copy .whl files to dist directory
        run: |
          mkdir -p dist
          find ./artifacts -name "*.whl" -exec cp {} ./dist \;

      - name: Copy .tar.gz files to dist directory
        run: |
          mkdir -p dist
          find ./artifacts -name "*.tar.gz" -exec cp {} ./dist \;

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-release.outputs.tag }}
          name: fluctuation-analysis-tools ${{ steps.get-release.outputs.release_name }}
          draft: false
          prerelease: false
          body: |
            This release was created based on the tag **${{ steps.get-release.outputs.tag }}**.
          files: |
            ./dist/*.whl
            ./dist/*.tar.gz

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
